### ISSUE TITLE
сыпет в лог - предупреждение

### ISSUE THREAD

**Issue by jorjik** [DivanDesign/EvolutionCMS.snippets.ddGetMultipleField#10]
version 3.4

```
Deprecated ordered parameters.

Ordered list of parameters is no longer allowed, use the “pass-by-name” style.

//Old styleddTools->verifyRenamedParams($params, $compliance);//Pass-by-nameddTools->verifyRenamedParams(['params' => $params,
	'compliance' => $compliance]);
```
Debug info https://i.imgur.com/dcN0wrQ.png

_вызов:_
				[[ddGetMultipleField?
					&inputString=`[*multi*]`
					&rowTpl=`multi.row`
				]]

**Comment by Ronef** [comment]
Просто обновите сниппет до последней версии и он перестанет, фиксили это как раз в версии 3.5.1.
